Repository KendryRSoto/ToDoList, pull requests merged in 2023-06, with the labels that each got.

#1 style: add comment app
  practi/src/App.jsx
Labels: style

#2 feat: add funtion app
  practi/src/App.jsx
  practi/src/components/Box-task.jsx
  practi/src/main.jsx
Labels: Feat

#4 Update README.md
  README.md
Labels: documentation, style

#5 Style: add styles app
  practi/package-lock.json
  practi/package.json
  practi/src/App.css
  practi/src/App.jsx
  practi/src/components/Box-task.jsx
  practi/src/main.jsx
  practi/src/styles/App.css
  practi/src/styles/style-Box-Task.css
Labels: style
